### ISSUE TITLE
Support for Caddy?

### ISSUE THREAD

**Issue by rmenessec** [miquels/webdavfs#4]
It's not clear to me from a quick look whether [Caddy](https://caddyserver.com/) with the [WebDAV plugin](https://github.com/hacdias/caddy-webdav) supports partial writes.

Can someone take a look, and possibly work with the plugin author to make this happen? Caddy is one of my new (as of last year) favorite things, and I'm using it anywhere I need or want something smaller and cleaner than Apache httpd.

I would like to contribute directly, but I don't know either Go or WebDAV anywhere near as well as the authors of the webdavfs or Caddy-WebDAV projects. 😒

**Comment by miquels** [comment]
The webdav plugin doesn't do webdav itself, it uses golang.org/x/net/webdav for that. Unfortunately, that library does not have support for partial writes, and it does not have (not even basic) support for If-Modified-Since / If-Unmodified-Since.

I fixed that a while ago, but I stopped working on the patches once I found out that [it's not trivial to contribute patches](https://golang.org/doc/contribute.html).

The repo is still online at [github.com/miquels/go-webdav-server](https://github.com/miquels/go-webdav-server). The patches don't all apply cleanly anymore though.

I'm not interested in pursuing this any further, but the latest person to send in [a patch](https://github.com/golang/net/commit/8e0cdda24ed423affc8f35c241e5e9b16180338e) was [ncw](https://github.com/ncw), he seems pretty active in the Go community, perhaps you could ask him.

**Comment by miquels** [comment]
I'm closing this as this is not a webdavfs issue, and nobody has stepped up to work on the golang webdav code (hey, I understand :) )
